---
- hosts: zabbix_servers
  max_fail_percentage: 1
  serial: 1
  accelerate: false
  sudo: true

  roles:
    - Azulinho.azulinho-google-dns
    - Azulinho.azulinho-apache
    - Azulinho.azulinho-mysql-server
    - Azulinho.azulinho-zabbix-server
    - Azulinho.azulinho-ssh-keys
    - Azulinho.azulinho-zabbix-agent
